-- Walrs dynamic colorscheme
-- Loads colors generated by walrs from ~/.cache/walrs/colors-nvim.lua

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
	vim.cmd("syntax reset")
end
vim.g.colors_name = "walrs"
vim.opt.termguicolors = true

-- Load walrs colors
local colors_path = vim.fn.expand("~/.cache/wal/colors-nvim.lua")
local ok, c = pcall(dofile, colors_path)
if not ok then
	vim.notify("Walrs colors not found at " .. colors_path .. "\nRun walrs to generate colors.", vim.log.levels.ERROR)
	return
end

local hl = function(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

-- Editor UI
hl("Normal", { fg = c.foreground, bg = "NONE" })
hl("NormalFloat", { fg = c.foreground, bg = c.black })
hl("FloatBorder", { fg = c.bright_black, bg = c.black })
hl("Cursor", { fg = c.background, bg = c.cursor })
hl("CursorLine", { bg = c.black })
hl("CursorLineNr", { fg = c.yellow, bold = true })
hl("LineNr", { fg = c.bright_black })
hl("SignColumn", { bg = "NONE" })
hl("ColorColumn", { bg = c.black })
hl("Visual", { bg = c.bright_black })
hl("VisualNOS", { bg = c.bright_black })
hl("Search", { fg = c.background, bg = c.yellow })
hl("IncSearch", { fg = c.background, bg = c.bright_yellow })
hl("CurSearch", { fg = c.background, bg = c.bright_yellow })
hl("MatchParen", { fg = c.bright_yellow, bold = true })

-- Statusline & Tabline
hl("StatusLine", { fg = c.foreground, bg = c.black })
hl("StatusLineNC", { fg = c.bright_black, bg = c.black })
hl("TabLine", { fg = c.bright_black, bg = c.black })
hl("TabLineFill", { bg = c.black })
hl("TabLineSel", { fg = c.foreground, bg = c.background })
hl("WinSeparator", { fg = c.bright_black })

-- Popup menu
hl("Pmenu", { fg = c.foreground, bg = c.black })
hl("PmenuSel", { fg = c.background, bg = c.blue })
hl("PmenuSbar", { bg = c.black })
hl("PmenuThumb", { bg = c.bright_black })

-- Messages
hl("ModeMsg", { fg = c.green, bold = true })
hl("MoreMsg", { fg = c.green })
hl("Question", { fg = c.green })
hl("WarningMsg", { fg = c.yellow })
hl("ErrorMsg", { fg = c.red })

-- Diff
hl("DiffAdd", { fg = c.green, bg = "NONE" })
hl("DiffChange", { fg = c.yellow, bg = "NONE" })
hl("DiffDelete", { fg = c.red, bg = "NONE" })
hl("DiffText", { fg = c.blue, bg = "NONE" })

-- Spelling
hl("SpellBad", { undercurl = true, sp = c.red })
hl("SpellCap", { undercurl = true, sp = c.yellow })
hl("SpellLocal", { undercurl = true, sp = c.cyan })
hl("SpellRare", { undercurl = true, sp = c.purple })

-- Folding
hl("Folded", { fg = c.bright_black, bg = c.black })
hl("FoldColumn", { fg = c.bright_black })

-- Misc UI
hl("Directory", { fg = c.blue })
hl("Title", { fg = c.purple, bold = true })
hl("NonText", { fg = c.bright_black })
hl("SpecialKey", { fg = c.bright_black })
hl("Whitespace", { fg = c.bright_black })
hl("EndOfBuffer", { fg = c.background })

-- Syntax highlighting
hl("Comment", { fg = c.bright_black, italic = true })
hl("Constant", { fg = c.purple })
hl("String", { fg = c.green })
hl("Character", { fg = c.green })
hl("Number", { fg = c.purple })
hl("Boolean", { fg = c.purple })
hl("Float", { fg = c.purple })
hl("Identifier", { fg = c.foreground })
hl("Function", { fg = c.cyan })
hl("Statement", { fg = c.red })
hl("Conditional", { fg = c.red })
hl("Repeat", { fg = c.red })
hl("Label", { fg = c.red })
hl("Operator", { fg = c.bright_yellow })
hl("Keyword", { fg = c.red })
hl("Exception", { fg = c.red })
hl("PreProc", { fg = c.yellow })
hl("Include", { fg = c.red })
hl("Define", { fg = c.purple })
hl("Macro", { fg = c.purple })
hl("PreCondit", { fg = c.yellow })
hl("Type", { fg = c.yellow })
hl("StorageClass", { fg = c.yellow })
hl("Structure", { fg = c.yellow })
hl("Typedef", { fg = c.yellow })
hl("Special", { fg = c.bright_yellow })
hl("SpecialChar", { fg = c.bright_yellow })
hl("Tag", { fg = c.blue })
hl("Delimiter", { fg = c.foreground })
hl("SpecialComment", { fg = c.bright_black })
hl("Debug", { fg = c.red })
hl("Underlined", { underline = true })
hl("Error", { fg = c.red })
hl("Todo", { fg = c.background, bg = c.yellow, bold = true })

-- Treesitter highlights
hl("@keyword", { fg = c.red })
hl("@keyword.repeat", { fg = c.red })
hl("@keyword.return", { fg = c.red })
hl("@keyword.function", { fg = c.red })
hl("@keyword.conditional", { fg = c.red })
hl("@keyword.exception", { fg = c.red })
hl("@keyword.import", { fg = c.red })
hl("@function", { fg = c.cyan })
hl("@function.call", { fg = c.cyan })
hl("@function.method", { fg = c.cyan })
hl("@function.method.call", { fg = c.cyan })
hl("@function.builtin", { fg = c.yellow })
hl("@constructor", { fg = c.yellow })
hl("@type", { fg = c.yellow })
hl("@type.builtin", { fg = c.yellow })
hl("@string", { fg = c.green })
hl("@character", { fg = c.green })
hl("@string.escape", { fg = c.bright_yellow })
hl("@variable", { fg = c.foreground })
hl("@variable.builtin", { fg = c.purple })
hl("@variable.parameter", { fg = c.blue })
hl("@variable.member", { fg = c.blue })
hl("@constant", { fg = c.purple })
hl("@constant.builtin", { fg = c.purple })
hl("@number", { fg = c.purple })
hl("@boolean", { fg = c.purple })
hl("@operator", { fg = c.bright_yellow })
hl("@punctuation.bracket", { fg = c.foreground })
hl("@punctuation.delimiter", { fg = c.foreground })
hl("@comment", { fg = c.bright_black, italic = true })
hl("@module", { fg = c.yellow })

-- LSP semantic tokens
hl("@lsp.type.function", { fg = c.cyan })
hl("@lsp.type.method", { fg = c.cyan })
hl("@lsp.type.variable", { fg = c.foreground })
hl("@lsp.type.parameter", { fg = c.blue })
hl("@lsp.type.property", { fg = c.blue })
hl("@lsp.type.type", { fg = c.yellow })
hl("@lsp.type.class", { fg = c.yellow })
hl("@lsp.type.struct", { fg = c.yellow })
hl("@lsp.type.enum", { fg = c.yellow })
hl("@lsp.type.enumMember", { fg = c.purple })
hl("@lsp.type.namespace", { fg = c.yellow })
hl("@lsp.type.keyword", { fg = c.red })

-- Diagnostics
hl("DiagnosticError", { fg = c.red })
hl("DiagnosticWarn", { fg = c.yellow })
hl("DiagnosticInfo", { fg = c.blue })
hl("DiagnosticHint", { fg = c.cyan })
hl("DiagnosticUnderlineError", { undercurl = true, sp = c.red })
hl("DiagnosticUnderlineWarn", { undercurl = true, sp = c.yellow })
hl("DiagnosticUnderlineInfo", { undercurl = true, sp = c.blue })
hl("DiagnosticUnderlineHint", { undercurl = true, sp = c.cyan })

-- Git signs
hl("GitSignsAdd", { fg = c.green })
hl("GitSignsChange", { fg = c.yellow })
hl("GitSignsDelete", { fg = c.red })

-- Nvim-tree
hl("NvimTreeNormal", { fg = c.foreground, bg = "NONE" })
hl("NvimTreeFolderIcon", { fg = c.blue })
hl("NvimTreeFolderName", { fg = c.blue })
hl("NvimTreeOpenedFolderName", { fg = c.blue, bold = true })
hl("NvimTreeRootFolder", { fg = c.purple })
hl("NvimTreeGitDirty", { fg = c.yellow })
hl("NvimTreeGitNew", { fg = c.green })
hl("NvimTreeGitDeleted", { fg = c.red })

-- Telescope
hl("TelescopeBorder", { fg = c.bright_black })
hl("TelescopePromptBorder", { fg = c.bright_black })
hl("TelescopeResultsBorder", { fg = c.bright_black })
hl("TelescopePreviewBorder", { fg = c.bright_black })
hl("TelescopeSelection", { bg = c.black })
hl("TelescopeMatching", { fg = c.yellow, bold = true })

-- Which-key
hl("WhichKey", { fg = c.cyan })
hl("WhichKeyGroup", { fg = c.purple })
hl("WhichKeyDesc", { fg = c.foreground })
hl("WhichKeySeparator", { fg = c.bright_black })

-- Indent blankline
hl("IblIndent", { fg = c.black })
hl("IblScope", { fg = c.bright_black })

-- Bufferline (basic, plugin may override)
hl("BufferLineFill", { bg = c.black })
hl("BufferLineBackground", { fg = c.bright_black, bg = c.black })
hl("BufferLineBufferSelected", { fg = c.foreground, bg = c.background, bold = true })
